template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "pedi1238"
__REPO__ = "lang-nso"
__UND2C__ = "nso"
__UNDEFINED__ = "Pedi"
__UND__ = "nso"
