template = "https://github.com/giellalt/template-lang-und"
rev_id = 296
template_sha = "879b03783ce7c34cc6b4dfc240164614f484a26e"

[replacements]
__GLOTTOLOG_ID__ = "pedi1238"
__REPO__ = "lang-nso"
__UND2C__ = "nso"
__UNDEFINED__ = "Pedi"
__UND__ = "nso"
