template = "https://github.com/giellalt/template-lang-und"
rev_id = 338
template_sha = "f8f3c0370220064ccae6868bc90707e0583f91c2"

[replacements]
__GLOTTOLOG_ID__ = "pedi1238"
__REPO__ = "lang-nso"
__UND2C__ = "nso"
__UNDEFINED__ = "Pedi"
__UND__ = "nso"
