[package]
name = "nso"
human_name = "Pedi"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.nso]
filename = "nso-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-nso"
platform = "windows"
uuid = "EA3ECE53-7919-4D2D-9E69-01E2BB6A2FE1"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.nso"
package = "speller-nso"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-nso-mso"
platform = "windows"
uuid = "9CF28CF3-FC0C-45B3-9600-90BD1018EB28"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-nso"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
